#!/bin/sh
set -veuo pipefail

cd "$(dirname "$0")/.."

cargo msrv --bisect --ignore-lockfile --include-all-patch-releases --toolchain-file
cargo clippy --fix --allow-dirty
cargo +nightly fmt
cargo test
INSTALL_VERSION="$NEW_VERSION" scripts/readme
