#!/bin/bash
set -euo pipefail
shopt -s inherit_errexit nullglob compat"${BASH_COMPAT=42}"

echo '```sh
$ cargo install save
```

```sh
$ save --help
```

```text
'"$(NO_COLOR=NO cargo run --manifest-path="$(dirname "$0")/../Cargo.toml" -- --help)"'
```' > "$(dirname "$0")/../README.md"
