#!/bin/bash
set -veuo pipefail
shopt -s inherit_errexit nullglob compat"${BASH_COMPAT=42}"

cd "$(dirname "$0")/.."

echo '```sh
$ cargo install
```

```sh
$ save --help
```

```text
'"$(NO_COLOR=NO MAX_TERM_WIDTH=70 cargo run -- --help)"'
```' > "$(dirname "$0")/../README.md"
