#!/bin/bash
set -veuo pipefail
shopt -s inherit_errexit nullglob compat"${BASH_COMPAT=42}"

cd "$(dirname "$0")/.."

declare install_args=""
if [[ -n "${INSTALL_VERSION:=}" ]]; then
  install_args=" --version $INSTALL_VERSION"
fi

echo '```sh
$ cargo install save'"${install_args}"'
```

```sh
$ save --help
```

```text
'"$(NO_COLOR=NO MAX_TERM_WIDTH=70 cargo run -- --help)"'
```' > "./README.md"
